# Generated by Django 5.1.15 on 2026-04-28 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('supplier', 'Supplier'), ('manufacturer', 'Manufacturer'), ('freight_forwarder', 'Freight Forwarder'), ('carrier', 'Carrier')], max_length=30)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=50)),
                ('additional_contacts', models.JSONField(blank=True, default=list)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('preferred_payment_method', models.CharField(blank=True, choices=[('wire', 'Wire Transfer'), ('ach', 'ACH'), ('check', 'Check'), ('card', 'Credit Card')], max_length=20)),
                ('website', models.URLField(blank=True)),
                ('portal_notes', models.TextField(blank=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
